adding module plume-web-jersey-info
Coreoz/Plume pull request #23
Opened 2023-07-18 16:34 UTC by Wail-LT

adding module plume-web-jersey-info

2023-07-19 09:15 UTC, amanteaux requested changes

2023-07-19 09:15 UTC, amanteaux commented on plume-framework-dependencies/pom.xml
> +        <metrics.version>4.1.2</metrics.version>
```suggestion
        <dropwizard-metrics.version>4.1.2</dropwizard-metrics.version>
```

2023-07-19 09:15 UTC, amanteaux commented on plume-web-jersey-info/README.md
> +This module provides multiple utilities to implement monitoring web-services
```suggestion
This module provides utilities to expose backend monitoring API similarly to what is offered by Spring Actuator:
- `/health`
- `/info`
- `/metrics`
```

2023-07-19 09:15 UTC, amanteaux commented on plume-web-jersey-info/README.md
> +Jackson
Le reste du README n'est pas bon.

Il faut expliquer rapidement comment utiliser le module. En ajoutant un exemple avec une classe WS qui expose les 3 API

2023-07-19 09:15 UTC, amanteaux commented on plume-web-jersey-info/src/main/java/com/coreoz/plume/jersey/info/configuration/PlmWebJerseyInfoConfigurationService.java
> +        return this.config.getObject("plm-web-jersey-info.info").unwrapped();
ça ne fait par d'erreur si ce n'est pas rempli ?

2023-07-19 09:15 UTC, amanteaux commented on plume-web-jersey-info/src/main/java/com/coreoz/plume/jersey/info/objectmapper/PlmWebJerseyInfoObjectMapper.java
> +public class PlmWebJerseyInfoObjectMapper extends ObjectMapper {
Il faut éviter d'étendre des classes quand on n'en a pas besoin.

Ici tu pourrais juste faire une méthode statique qui retourne un `ObjetMapper`.

2023-07-19 09:15 UTC, amanteaux commented on plume-web-jersey-info/src/main/java/com/coreoz/plume/jersey/info/objectmapper/PlmWebJerseyInfoObjectMapper.java
> +public class PlmWebJerseyInfoObjectMapper extends ObjectMapper {
```suggestion
public class JerseyInfoObjectMapper {
```

2023-07-19 09:15 UTC, amanteaux commented on plume-web-jersey-info/src/main/java/com/coreoz/plume/jersey/info/configuration/PlmWebJerseyInfoConfigurationService.java
> +public class PlmWebJerseyInfoConfigurationService {
```suggestion
public class JerseyInfoConfigurationService {
```

2023-07-19 09:15 UTC, amanteaux commented on plume-web-jersey-info/src/main/java/com/coreoz/plume/jersey/info/health/HealthCheckService.java
> +    public static final HealthCheckModule objectMapperModule = new HealthCheckModule();
C'est spécifique à Jackson et non utilisé ici => la déclération devrait être faite dans ta classe object mapper

2023-07-19 09:15 UTC, amanteaux commented on plume-web-jersey-info/src/main/java/com/coreoz/plume/jersey/info/objectmapper/PlmWebJerseyInfoObjectMapper.java
> +public class PlmWebJerseyInfoObjectMapper extends ObjectMapper {
D'ailleurs, il faudrait aussi changer le package : `objectmapper` c'est pas très explicite, tu pourrais plutôt utiliser `json`

2023-07-19 09:15 UTC, amanteaux commented on plume-web-jersey-info/src/main/java/com/coreoz/plume/jersey/info/health/HealthCheckService.java
> +public class HealthCheckService {
En fait, il n'y a aucune raison que ce soit un service si ?

Tu pourrais supprimer les annotation d'injection de dépendances et juste renommer la classe en `JerseyInfoHealthCheck`

2023-07-19 09:15 UTC, amanteaux commented on plume-web-jersey-info/src/main/java/com/coreoz/plume/jersey/info/health/HealthCheckService.java
> +    public static final HealthCheckModule objectMapperModule = new HealthCheckModule();
Même chose sur les autres classes info et metrics

2023-07-19 09:15 UTC, amanteaux commented on plume-web-jersey-info/src/main/java/com/coreoz/plume/jersey/info/metrics/MetricsService.java
> +    }
Tu pourrais ajouter la méthode `registerJvmMetrics()` qui ferait :
```java
        metricRegistry.registerAll("memory-usage", new MemoryUsageGaugeSet());
        metricRegistry.registerAll("thread-states", new ThreadStatesGaugeSet());
```

2023-07-19 09:15 UTC, amanteaux commented on plume-web-jersey-info/src/main/java/com/coreoz/plume/jersey/info/health/HealthCheckService.java
> +
Tu pourrais ajouter la méthode `registerDatabaseHealthCheck(TransactionManager transactionManager)` qui ferait un register directement du database Health check ?

2023-07-19 09:15 UTC, amanteaux commented on plume-web-jersey-info/src/main/java/com/coreoz/plume/jersey/info/health/HealthCheckService.java
> +public class HealthCheckService {
Ou même `HealthCheckBuilder`, et la méthode build retournerait un `Provider<HealthStatus>`

2023-07-19 09:15 UTC, amanteaux commented on plume-web-jersey-info/src/main/java/com/coreoz/plume/jersey/info/info/InfoService.java
> +public class InfoService {
```suggestion
public class ApplicationInfoService {
```

2023-07-19 09:15 UTC, amanteaux commented on plume-web-jersey-info/src/main/java/com/coreoz/plume/jersey/info/info/InfoService.java
> +    public String getAppInfo() {
Cette méthode devrait être statique et être appelée dans le constructeur pour être enregistré dans une constante : le résultat ne changera jamais au cours de la vie de l'application

2023-07-19 09:15 UTC, amanteaux commented on plume-web-jersey-info/src/main/java/com/coreoz/plume/jersey/info/health/HealthCheckService.java
> +public class HealthCheckService {
Même chose pour `MetricsService`

2023-07-19 09:15 UTC, amanteaux commented on plume-web-jersey-info/pom.xml
> +			<groupId>commons-validator</groupId>
Ne sert à rien si ?

2023-07-19 09:15 UTC, amanteaux commented on plume-web-jersey-info/pom.xml
> +			<groupId>com.google.guava</groupId>
Est utilisé ?

2023-07-19 09:15 UTC, amanteaux commented on plume-web-jersey-info/pom.xml
> +		</dependency>
Tout ça doit être remplacé juste par :
```xml
<dependency>
    <groupId>javax.inject</groupId>
    <artifactId>javax.inject</artifactId>
</dependency>
```

2023-07-19 09:15 UTC, amanteaux commented on plume-web-jersey-info/pom.xml
> +			<artifactId>javax.servlet-api</artifactId>
A supprimer

2023-07-19 09:15 UTC, amanteaux commented on plume-web-jersey-info/pom.xml
> +
inutile

2023-07-19 09:15 UTC, amanteaux commented on plume-web-jersey-info/pom.xml
> +			<groupId>com.squareup.okhttp3</groupId>
Inutile

2023-07-19 14:26 UTC, Wail-LT commented on plume-web-jersey-info/README.md
> +Jackson
Yes je voulais avoir une validation de l'implémentation avant d'attaquer le readme

2023-07-19 14:27 UTC, Wail-LT commented on plume-web-jersey-info/src/main/java/com/coreoz/plume/jersey/info/configuration/PlmWebJerseyInfoConfigurationService.java
> +        return this.config.getObject("plm-web-jersey-info.info").unwrapped();
Nop car on a un fallback sur la conf par default.

2023-07-19 14:27 UTC, Wail-LT commented on plume-web-jersey-info/src/main/java/com/coreoz/plume/jersey/info/objectmapper/PlmWebJerseyInfoObjectMapper.java
> +public class PlmWebJerseyInfoObjectMapper extends ObjectMapper {
Ok avoir un provider

2023-07-19 15:35 UTC, Wail-LT commented on plume-web-jersey-info/pom.xml
> +			<groupId>com.google.guava</groupId>
nop

2023-07-20 06:32 UTC, Wail-LT commented on plume-web-jersey-info/README.md
> +Jackson
J'ai refait le readme

2023-07-20 10:13 UTC, amanteaux commented
Il faudrait supprimer partout partout le préfixe `PlmWeb`, ce n'est pas lisible du tout

2023-07-20 10:24 UTC, amanteaux requested changes

2023-07-20 10:24 UTC, amanteaux commented on plume-web-jersey-info/pom.xml
> +            <artifactId>plume-db</artifactId>
Il faudrait mettre la dépendance en `optional` de manière à pouvoir ne pas exposer le endpoint si on veut, et du coup ne pas ramener plume db

2023-07-20 10:24 UTC, amanteaux commented on plume-web-jersey-info/README.md
> +    private final ObjectMapper objectMapper = PlmWebJerseyInfoObjectMapperProvider.get();
ça ne semble pas utile de définir ça en variable de classe

2023-07-20 13:37 UTC, Wail-LT commented on plume-web-jersey-info/pom.xml
> +			<groupId>commons-validator</groupId>
supprimé

2023-07-20 19:53 UTC, Wail-LT commented on plume-web-jersey-info/src/main/java/com/coreoz/plume/jersey/info/objectmapper/PlmWebJerseyInfoObjectMapper.java
> +public class PlmWebJerseyInfoObjectMapper extends ObjectMapper {
Comme vu ensemble j'ai directement surchargé l'objectMapper de plume-web-jersey

2023-07-20 19:55 UTC, Wail-LT commented on plume-web-jersey-info/src/main/java/com/coreoz/plume/jersey/info/info/InfoService.java
> +    public String getAppInfo() {
J'en ai fait un provider, l'objet ApplicationInfo est récupérable via l'injection de dépendance, je trouve ça plus simple.

Si tu veux on peut en discuter 😁

2023-07-20 19:59 UTC, Wail-LT commented on plume-web-jersey-monitoring/src/main/java/com/coreoz/plume/jersey/monitoring/guice/GuiceJacksonWithMetricsModule.java
> +}
J'hésite à mettre ça dans le `GuiceJerseyMonitoringModule`.

Je me dis que séparer ces deux modules permet de mettre en avant le fait que le `GuiceJacksonWithMetricsModule` est une surcharge de `GuiceJacksonModule`.

Quel serait ton avis là dessus @amanteaux ?

2023-07-21 10:30 UTC, amanteaux requested changes

2023-07-21 10:30 UTC, amanteaux commented on plume-web-jersey-monitoring/README.md
> +Plume Web Jersey info
```suggestion
Plume Web Jersey monitoring
```

2023-07-21 10:30 UTC, amanteaux commented on plume-web-jersey-monitoring/README.md
> +It contains the basic application information retrieved from the `Pom.xml` file.
```suggestion
It contains the basic application information retrieved from the `pom.xml` file.
```

2023-07-21 10:30 UTC, amanteaux commented on plume-web-jersey-monitoring/README.md
> +            .registerDatabaseHealthCheck()
Il manque le TransactionManager en paramètre non ?

2023-07-21 10:30 UTC, amanteaux commented on plume-web-jersey-monitoring/pom.xml
> +        </dependency>
Comme finalement tu as Guice, tu peux remplacer ça par Guice (qui est pour le moment déclaré un peu en dessous) ?

2023-07-21 10:30 UTC, amanteaux commented on plume-web-jersey-monitoring/src/main/java/com/coreoz/plume/jersey/monitoring/json/JerseyMonitoringObjectMapperProvider.java
> +    );
Plutôt que de créer des variables statiques, tu veux pas juste tout déclarer dans le constructeur au moment du register module ?

2023-07-21 10:30 UTC, amanteaux commented on plume-web-jersey-monitoring/src/main/java/com/coreoz/plume/jersey/monitoring/utils/health/beans/HealthStatus.java
> +        this.healthChecksResults = Map.copyOf(healthChecksResults);
Pour quoi faire ? Tu veux pas juste utiliser `@Value` sur la classe `HealthStatus` sans faire de traitement ?

2023-07-21 10:30 UTC, amanteaux commented on plume-web-jersey-monitoring/src/main/java/com/coreoz/plume/jersey/monitoring/utils/info/ApplicationInfoProvider.java
> +            throw new RuntimeException("Failed to retrieve the application information", e);
Plutôt que de faire un try catch et rethrow une runtime exception, tu veux pas juste déclarer que ton constructeur peut throw l'exception de modelReader ?

2023-07-21 10:30 UTC, amanteaux commented on plume-web-jersey-monitoring/src/main/java/com/coreoz/plume/jersey/monitoring/utils/info/beans/ApplicationInfo.java
> +public class ApplicationInfo {
Tu veux pas remplacer le boilerplate par `@Value` ?

2023-07-21 10:30 UTC, amanteaux commented on plume-web-jersey-monitoring/README.md
> +        return this.infoService.getAppInfo();
ça ne compile pas. Il faut que tu testes rapidement ta classe présentée en exemple :P

2023-07-21 10:30 UTC, amanteaux commented on plume-web-jersey-monitoring/src/main/java/com/coreoz/plume/jersey/monitoring/guice/GuiceJacksonWithMetricsModule.java
> +}
En fait je comprends l'idée d'exposer directement l'objet `ApplicationInfo` dans le système d'injection de dépendances. Mais aujourd'hui on ne met que des services ou du code contenant de la logique dans le système d'injection de dépendances. Pour un cas aussi simples que ça, j'aurais tendance à ne pas proposer le module `GuiceJerseyMonitoringModule`. Et donc dans les projets, il faudrait récupérer l'instance de `ApplicationInfoProvider` et appeler la méthode `get()` dessus

2023-07-21 10:30 UTC, amanteaux commented on plume-web-jersey-monitoring/src/main/java/com/coreoz/plume/jersey/monitoring/guice/GuiceJacksonWithMetricsModule.java
> +}
Du coup si pas de GuiceJerseyMonitoringModule, pas de problème avec le GuiceJacksonWithMetricsModule :P

2023-07-21 10:33 UTC, Wail-LT commented on plume-web-jersey-monitoring/README.md
> +            .registerDatabaseHealthCheck()
Yes sorry erreur d'inattention

2023-07-21 10:35 UTC, Wail-LT commented on plume-web-jersey-monitoring/src/main/java/com/coreoz/plume/jersey/monitoring/utils/info/ApplicationInfoProvider.java
> +            throw new RuntimeException("Failed to retrieve the application information", e);
Yes j'avais compris que tu n'étais pas trop fan des checkedExceptions

2023-07-21 10:37 UTC, Wail-LT commented on plume-web-jersey-monitoring/src/main/java/com/coreoz/plume/jersey/monitoring/utils/info/beans/ApplicationInfo.java
> +public class ApplicationInfo {
Yes, je ne l'ai pas fait, car lombok n'est pas utilisé dans les autres modules

2023-07-21 10:40 UTC, Wail-LT commented on plume-web-jersey-monitoring/src/main/java/com/coreoz/plume/jersey/monitoring/guice/GuiceJacksonWithMetricsModule.java
> +}
Ok je comprends !

2023-07-21 10:49 UTC, Wail-LT commented on plume-web-jersey-monitoring/src/main/java/com/coreoz/plume/jersey/monitoring/utils/health/beans/HealthStatus.java
> +        this.healthChecksResults = Map.copyOf(healthChecksResults);
Je ne suis pas sûr que ça y change quelque chose.

`Map.copyOf` c'est pour éviter que les modifications apportés à `healthChecksResults` qui est passé en paramètre impactent l'objet `HealthStatus`.

Mais c'est peut-être overkill

2023-07-21 10:51 UTC, Wail-LT commented on plume-web-jersey-monitoring/README.md
> +        return this.infoService.getAppInfo();
Désolé !

2023-07-21 11:06 UTC, merged