implement PaginatedQueries for QueryDsl
Coreoz/Plume pull request #34
Opened 2024-06-11 16:29 UTC by lucas-amiaud

2024-09-17 12:45 UTC, amanteaux requested changes

2024-09-17 12:45 UTC, amanteaux commented on plume-db-querydsl/src/main/java/com/coreoz/plume/db/querydsl/pagination/Page.java
> +    public <U> Page<U> mapElements(Function<T, U> mapper) {
A quoi sert cette fonction ? Je veux bien en discuter pour voir si on ne peut pas faire autrement

2024-09-17 12:45 UTC, amanteaux commented on plume-db-querydsl/src/main/java/com/coreoz/plume/db/querydsl/pagination/Pageable.java
> +    private final int size;
`pageSize` ?

2024-09-17 12:45 UTC, amanteaux commented on plume-db-querydsl/src/main/java/com/coreoz/plume/db/querydsl/pagination/SQLPaginatedQuery.java
> +public class SQLPaginatedQuery<U> {
SqlPaginatedQuery

2024-09-17 12:45 UTC, amanteaux commented on plume-db-querydsl/src/main/java/com/coreoz/plume/db/querydsl/pagination/Pageable.java
> +public class Pageable {
PageRequest ?

2024-09-17 12:45 UTC, amanteaux commented on plume-db-querydsl/src/main/java/com/coreoz/plume/db/querydsl/pagination/SortOption.java
> +    private static Order orderDirection(@Nullable String sortDirection) {
Ici c'est non null, et d'ailleurs c'est upperCaseSortDirection

2024-09-17 12:45 UTC, amanteaux commented on plume-db-querydsl/src/main/java/com/coreoz/plume/db/querydsl/pagination/SortOption.java
> +    public static SortOption from(@Nullable SortPath path, @Nullable String sortDirection) {
Dans quels cas tu penses utiliser le paramètre sortDirection en string plutôt qu'en `Order` ?

2024-09-17 12:45 UTC, amanteaux commented on plume-db-querydsl/src/main/java/com/coreoz/plume/db/querydsl/pagination/SortPath.java
> +public interface SortPath {
Pourquoi passer par cette interface au lieu de juste `StringPath` ?

2024-09-17 12:45 UTC, amanteaux commented on plume-db-querydsl/src/main/java/com/coreoz/plume/db/querydsl/pagination/SortOption.java
> +public class SortOption {
Est-ce que finalement on ne pourrait pas supprimer cette classe et nous appuyer uniquement sur `OrderSpecifier` de querydsl ?

2024-09-17 12:45 UTC, amanteaux commented on plume-db-querydsl/src/main/java/com/coreoz/plume/db/querydsl/pagination/Pageable.java
> +    public Pageable(Integer page, Integer size) {
Je trouve ça dommage de mettre autant de logique ici alors que ce ne sera qu'utilisé pour utiliser `SqlPaginatedQuery`. On pourrait juste mettre un record avec des attributs non nulls. La logique de calcul serait ensuite concentrée dans `SqlPaginatedQuery`

2024-09-17 12:45 UTC, amanteaux commented on plume-db-querydsl/src/main/java/com/coreoz/plume/db/querydsl/pagination/SQLPaginatedQuery.java
> +    public Page<U> paginate(Pageable pageable) {
`fetchPage` ?

2024-09-17 12:45 UTC, amanteaux commented on plume-db-querydsl/src/main/java/com/coreoz/plume/db/querydsl/pagination/SQLPaginatedQuery.java
> +        return this.paginate(Pageable.ofPageSize(size).withPage(page));
Cette méthode devrait pouvoir appeler fetchPage sans avoir à créer un nouvel objet

2024-09-17 12:45 UTC, amanteaux commented on plume-db-querydsl/src/main/java/com/coreoz/plume/db/querydsl/pagination/SQLPaginatedQuery.java
> +    private Page<U> fetchPage(SQLQuery<U> baseQuery, Pageable pageable) {
Ce serait bien d'avoir une méthode fetchList qui retourne la page demandée sans retourner les métriques : ça évite une requête SQL

2024-09-17 12:45 UTC, amanteaux commented on plume-db-querydsl/src/main/java/com/coreoz/plume/db/querydsl/pagination/SQLPaginatedQuery.java
> +    private Page<U> fetchPage(SQLQuery<U> baseQuery, Pageable pageable) {
Idéalement, il faudrait aussi fournir une implémentation de `fetchSlice` qui évite aussi de faire une requête supplémentaire : https://stackoverflow.com/questions/49918979/page-vs-slice-when-to-use-which

2024-09-17 12:59 UTC, amanteaux commented
Puis une fois qu'on sera alignés, il faudra documenter cette fonction

2024-09-17 13:19 UTC, lucas-amiaud commented on plume-db-querydsl/src/main/java/com/coreoz/plume/db/querydsl/pagination/Page.java
> +    public <U> Page<U> mapElements(Function<T, U> mapper) {
C'est pour mapper les éléments dans la liste retournée, sans toucher à la pagination. Ca nous a beaucoup été utile sur unibail pour ajouter des infos qui sont pas en base, ou formatter des choses dans le bean de retour

2024-09-18 08:33 UTC, lucas-amiaud commented on plume-db-querydsl/src/main/java/com/coreoz/plume/db/querydsl/pagination/SQLPaginatedQuery.java
> +public class SQLPaginatedQuery<U> {
je voulais garder la syntaxe de QueryDsl qui préfixe ses classes par SQL en majuscule, mais je peux changer s'il faut

2024-09-18 08:51 UTC, lucas-amiaud commented on plume-db-querydsl/src/main/java/com/coreoz/plume/db/querydsl/pagination/Pageable.java
> +    public Pageable(Integer page, Integer size) {
Je suis assez partagé sur cet avis : c'est plus un builder de pagination qui permet aussi de ne pas tout renseigner. Je trouvais l'interface plutot user friendly. Et comme ca la responsabilité de SqlPaginatedQuery reste uniquement d'exécuter la requête, sans avoir à gérer les erreurs sur les consignes de pagination

2024-09-18 09:27 UTC, lucas-amiaud commented on plume-db-querydsl/src/main/java/com/coreoz/plume/db/querydsl/pagination/SortOption.java
> +public class SortOption {
pareil que pour pageable, ca fait un petite abstraction pour avoir une interface un peu user friendly qui gère les mauvais saisies, surtout quand ca vient d'un webservice

2024-09-18 12:32 UTC, amanteaux requested changes
+ Faire la doc qui donne un exemple de Dao paginé avec le Web service associé

2024-09-18 12:32 UTC, amanteaux commented on plume-db-querydsl/src/main/java/com/coreoz/plume/db/querydsl/pagination/Pageable.java
> +    private final int page;
pageNumber

2024-09-18 12:32 UTC, amanteaux commented on plume-db-querydsl/src/main/java/com/coreoz/plume/db/querydsl/pagination/Pageable.java
> +public class Pageable {
+ ajouter java doc pour dire que la page commence à 1 et un exemple avec le pageSize

2024-09-18 12:32 UTC, amanteaux commented on plume-db-querydsl/src/main/java/com/coreoz/plume/db/querydsl/pagination/Pageable.java
> +public class Pageable {
A sortir dans le module plume-db

2024-09-18 12:32 UTC, amanteaux commented on plume-db-querydsl/src/main/java/com/coreoz/plume/db/querydsl/pagination/Page.java
> +public class Page<T> {
A sortir dans le module plume-db

2024-09-18 12:32 UTC, amanteaux commented on plume-db-querydsl/src/main/java/com/coreoz/plume/db/querydsl/pagination/Page.java
> +    public <U> Page<U> mapElements(Function<T, U> mapper) {
renommer en `map`

2024-09-18 12:33 UTC, amanteaux commented on plume-db-querydsl/pom.xml
> +			<artifactId>lombok</artifactId>
Provided

2024-09-18 15:26 UTC, amanteaux requested changes

2024-09-18 15:26 UTC, amanteaux commented on plume-db/src/main/java/com/coreoz/plume/db/pagination/Page.java
> +            this.elements.stream().map(mapper).collect(Collectors.toList()),
From Sonar: Replace this usage of 'Stream.collect(Collectors.toList())' with 'Stream.toList()' and ensure that the list is unmodified.

2024-09-18 15:26 UTC, amanteaux commented on plume-db/src/main/java/com/coreoz/plume/db/pagination/Pageable.java
> +public interface Pageable<T> {
Je renommerai bien cette interface en `Sliceable`

2024-09-18 15:26 UTC, amanteaux commented on plume-db/src/main/java/com/coreoz/plume/db/pagination/Pageable.java
> + * Common interface for paginated or sliced data structures.
Il faudrait ajouter les liens vers les structures : `Common interface for {@link Page} or {@link Slice} data structures.`

2024-09-18 15:26 UTC, amanteaux commented on plume-db/src/main/java/com/coreoz/plume/db/pagination/Pageable.java
> +    long size();
Je crois qu'il faut supprimer ce paramètre : il n'existe pas réellement dans la Slice (on renseigne uniquement pageRequest.limit() dans ce cas, ce qui ne respecte pas cette spec, qui n'est respectée que pour la page)

2024-09-18 15:26 UTC, amanteaux commented on plume-db/src/main/java/com/coreoz/plume/db/pagination/PageableRequest.java
> + * @param pageSize the size of the page queried (cannot be < 1)
Je le dirais plutôt dans l'autre sens : must be >= 1

2024-09-18 15:26 UTC, amanteaux commented on plume-db/src/main/java/com/coreoz/plume/db/pagination/Page.java
> +    public <U> Page<U> map(Function<T, U> mapper) {
Il faudrait documenter cette méthode en y ajoutant un exemple

2024-09-18 15:26 UTC, amanteaux commented on plume-db-querydsl/src/test/java/com/coreoz/plume/db/querydsl/pagination/SqlPaginatedQueryTest.java
> +        user.setName("To fetch");
Idéalement utilise l'instruction @BeforeClass, fait une boucle, et insère 150 utilisateurs :P.

Dans tes 2 tests ensuite, tu pourras vérifier les bons nombres

2024-09-18 15:26 UTC, amanteaux commented on plume-db-querydsl/src/main/java/com/coreoz/plume/db/querydsl/pagination/SqlPaginatedQuery.java
> + * Paginated query implementation with Query DSL library
`Paginated query implementation with Querydsl`

2024-09-18 15:26 UTC, amanteaux commented on plume-db-querydsl/src/main/java/com/coreoz/plume/db/querydsl/pagination/SqlPaginatedQuery.java
> + * public Page<User> fetchAsync(@Suspended AsyncResponse asyncResponse) {
Il est bizarre le `fetchAsync(@Suspended AsyncResponse asyncResponse)` ici

2024-09-18 15:26 UTC, amanteaux commented on plume-db/src/main/java/com/coreoz/plume/db/pagination/Page.java
> +    List<T> elements,
Tu peux ajouter l'annotation NotNull ?

2024-09-18 15:26 UTC, amanteaux commented on plume-db/src/main/java/com/coreoz/plume/db/pagination/Page.java
> +public record Page<T>(
Il faudrait commenter les paramètres pour bien préciser à quoi ça correspond, et rappeler que la première page a le number 1

2024-09-18 15:26 UTC, amanteaux commented on plume-db/src/main/java/com/coreoz/plume/db/pagination/Slice.java
> +    List<T> elements,
Il faudrait ajouter l'annotation @NotNull

2024-09-18 15:26 UTC, amanteaux commented on plume-db/src/main/java/com/coreoz/plume/db/pagination/Slice.java
> +public record Slice<T>(
Il faudrait rapidement documenter les paramètres

2024-09-18 15:26 UTC, amanteaux commented on plume-db-querydsl/src/main/java/com/coreoz/plume/db/querydsl/pagination/SqlPaginatedQuery.java
> +    public static <U> SqlPaginatedQuery<U> fromQuery(SQLQuery<U> sqlQuery) {
Il faudrait ajouter l'annotation @NotNull en entrée et sortie

2024-09-18 15:26 UTC, amanteaux commented on plume-db-querydsl/src/main/java/com/coreoz/plume/db/querydsl/pagination/SqlPaginatedQuery.java
> +    public <E extends Comparable<E>> SqlPaginatedQuery<U> withSort(Expression<E> expression, Order sortDirection) {
Il faudrait ajouter l'annotation @NotNull en entrée et sortie

2024-09-18 15:26 UTC, amanteaux commented on plume-db-querydsl/src/main/java/com/coreoz/plume/db/querydsl/pagination/SqlPaginatedQuery.java
> +    public Page<U> fetchPage(PageableRequest pageRequest) {
Il faudrait ajouter l'annotation @NotNull en entrée et sortie

2024-09-18 15:26 UTC, amanteaux commented on plume-db-querydsl/src/main/java/com/coreoz/plume/db/querydsl/pagination/SqlPaginatedQuery.java
> +    public Slice<U> fetchSlice(PageableRequest pageRequest) {
Il faudrait ajouter l'annotation @NotNull en entrée et sortie

2024-09-18 15:26 UTC, amanteaux commented on plume-db-querydsl/src/main/java/com/coreoz/plume/db/querydsl/pagination/SqlPaginatedQuery.java
> +    private Page<U> fetchPage(SQLQuery<U> baseQuery, PageableRequest pageRequest) {
Pourquoi séparer les méthodes privées et publiques ? Enfin j'ai l'impression qu'ajouter des méthodes statiques n'apporte pas grand chose, on pourrait directement faire l'implémentation dans les méthodes publiques et supprimer ces 2 méthodes privées

2024-09-18 15:26 UTC, amanteaux commented on plume-db-querydsl/src/test/java/com/coreoz/plume/db/querydsl/pagination/SqlPaginatedQueryTest.java
> +public class SqlPaginatedQueryTest {
Idéalement, il faudrait demander à chatgpt d'ajouter plus de tests :P

2024-09-19 08:18 UTC, amanteaux requested changes

2024-09-19 08:18 UTC, amanteaux commented on plume-db-querydsl/src/test/java/com/coreoz/plume/db/querydsl/pagination/SqlPaginatedQueryTest.java
> +        assertThat(page.hasMore()).isFalse();
Ce serait bien de faire des tests plus précis, tu sais que tu as 10 utilisateurs, donc tu peux savoir que le nombre de pages est 1, que tu as 10 éléments au total etc. Là les tests ne permettent pas de vérifier la bonne cohérence de tous les chiffres calculés

2024-09-19 08:18 UTC, amanteaux commented on plume-db/src/main/java/com/coreoz/plume/db/pagination/Page.java
> + * @param currentPage the current page
`@param currentPage the current page number, starts at 1`

2024-09-19 08:18 UTC, amanteaux commented on plume-db/src/main/java/com/coreoz/plume/db/pagination/Slice.java
> + * @param hasMore boolean set to true if there is another slice after
`@param hasMore boolean set to true if another slice is available after this one`

2024-09-19 10:01 UTC, merged