[#33] Provide more health metrics
Coreoz/Plume pull request #35
Opened 2024-08-23 10:11 UTC by Wail-LT

related to issue #33

2024-09-06 12:25 UTC, lucas-amiaud commented on plume-db/src/main/java/com/coreoz/plume/db/transaction/HikariDataSources.java
> +    public static HikariConfig createHikariConfig(Config config, String prefix) {
pourquoi pas ! mais si tu l'a changé c'est que c'est réutilisé ailleurs ?

2024-09-09 07:28 UTC, Wail-LT commented on plume-db/src/main/java/com/coreoz/plume/db/transaction/HikariDataSources.java
> +    public static HikariConfig createHikariConfig(Config config, String prefix) {
Bonne question, ce n'est pas moi qui ai modifié ce code, @amanteaux ?

2024-09-09 07:29 UTC, lucas-amiaud commented on plume-db/src/main/java/com/coreoz/plume/db/transaction/HikariDataSources.java
> +    public static HikariConfig createHikariConfig(Config config, String prefix) {
ha okay !
non c'était juste pour savoir si ca avait à voir avec tes évols :)

2024-09-09 07:31 UTC, lucas-amiaud commented
Ok pour moi !

2024-09-17 13:00 UTC, amanteaux requested changes
Il faudrait aussi mettre à jour la documentation avec tout ça

2024-09-17 13:00 UTC, amanteaux commented on plume-db/src/main/java/com/coreoz/plume/db/transaction/HikariDataSources.java
>  	public static DataSource fromConfig(Config config, String prefix) {
Ce serait plus simple de retourner directement un `HikariDataSource` non ?

2024-09-17 13:00 UTC, amanteaux commented on plume-db/src/main/java/com/coreoz/plume/db/transaction/HikariDataSources.java
>  public class HikariDataSources {
Par contre, il manque le code dans `DataSourceModule` et `DataSourceProvider` pour exposer correctement la datasource Hikari non ?

2024-09-17 13:00 UTC, amanteaux commented on plume-web-jersey-monitoring/src/main/java/com/coreoz/plume/jersey/monitoring/utils/metrics/MetricsCheckBuilder.java
> +    }
Il faudrait ajouter un test d'intégration avec ça pour vérifier qu'on récupère bien toutes les métriques et que c'est ok. Tu peux voir avec chatgpt pour t'aider à écrire le test :)

2024-10-14 09:59 UTC, Wail-LT commented on plume-db/src/main/java/com/coreoz/plume/db/transaction/HikariDataSources.java
>  	public static DataSource fromConfig(Config config, String prefix) {
En effet ! 

C'est corrigé.

2024-10-14 09:59 UTC, Wail-LT commented on plume-db/src/main/java/com/coreoz/plume/db/transaction/HikariDataSources.java
>  public class HikariDataSources {
Je ne suis pas sûr de comprendre, si tu as 5 minutes, je veux bien qu'on en discute

2024-10-14 09:59 UTC, Wail-LT commented on plume-web-jersey-monitoring/src/main/java/com/coreoz/plume/jersey/monitoring/utils/metrics/MetricsCheckBuilder.java
> +    }
Yes j'ajoute ça !

2024-10-14 10:00 UTC, Wail-LT commented on plume-db/src/main/java/com/coreoz/plume/db/transaction/HikariDataSources.java
>  public class HikariDataSources {
C'est une class static, pas besoin d'DI si ?

2024-10-14 15:24 UTC, amanteaux requested changes

2024-10-14 15:24 UTC, amanteaux commented on plume-db/src/main/java/com/coreoz/plume/db/transaction/HikariDataSourceProvider.java
> +public class HikariDataSourceProvider implements DataSourceProvider {
Ce serait pas plus simple de juste garder `DataSourceProvider` et mettre le code de cette classe dedans ?

2024-10-14 15:24 UTC, amanteaux commented on plume-db/src/main/java/com/coreoz/plume/db/transaction/HikariDataSourceProvider.java
> +    }
Je pense qu'on peut supprimer ce constructeur, il n'a pas vraiment de sens en fait. Si quelqu'un veut créer une autre datasource, il appelera juste `HikariDataSources.fromConfig(...)`
    }

2024-10-14 15:24 UTC, amanteaux commented on plume-db/src/main/java/com/coreoz/plume/db/guice/DataSourceModule.java
> +        bind(DataSourceProvider.class).to(HikariDataSourceProvider.class);
Cette ligne ne sert pas vraiment. Par contre il manque la ligne: `bind(HikariDataSource.class).toProvider(DataSourceProvider.class)`

2024-10-14 15:41 UTC, Wail-LT commented on plume-db/src/main/java/com/coreoz/plume/db/transaction/HikariDataSourceProvider.java
> +    }
Ah oui pas faux !

2024-10-14 15:41 UTC, Wail-LT commented on plume-db/src/main/java/com/coreoz/plume/db/transaction/HikariDataSourceProvider.java
> +public class HikariDataSourceProvider implements DataSourceProvider {
On ne veut pas laisser le choix d'avoir un autre Datasource que Hikarie ?

2024-10-14 15:54 UTC, amanteaux commented on plume-db/src/main/java/com/coreoz/plume/db/transaction/HikariDataSourceProvider.java
> +public class HikariDataSourceProvider implements DataSourceProvider {
Si si on va le permettre, il suffira juste d'implémenter son propre `Provider<DataSource>`. Par contre en y repensant, peut-être qu'il faudrait tout de même garder le nom de `HikariDataSourceProvider` à la place de `DataSourceProvider` qui est moins clair sur le rôle du provider.

2024-10-15 08:19 UTC, Wail-LT commented on plume-db/src/main/java/com/coreoz/plume/db/transaction/HikariDataSourceProvider.java
> +public class HikariDataSourceProvider implements DataSourceProvider {
Justement je ne suis pas sûr qu'en implémentant un Provider<DataSource> cela fonctionne.

`public class CustomDataSourceProvider implements Provider<DataSource>;`

`bind(HikariDataSourceProvider.class).to(CustomDataSourceProvider.class);`
Ça ne fonctionnera pas, HikariDataSources != Datasource.

2024-11-07 16:57 UTC, merged