Add a new annotation and an interceptor to control and check content …
Coreoz/Plume pull request #36
Opened 2024-09-04 14:07 UTC by benoitvasseur

…size of bodies and files

Will need an update after jersey migration to jakarta

2024-09-17 13:47 UTC, amanteaux requested changes
Il faudrait aussi ajouter une documentation dans le fichier `README.md` du module pour expliquer comment l'utiliser

2024-09-17 13:47 UTC, amanteaux commented on plume-web-jersey/src/main/java/com/coreoz/plume/jersey/security/control/ContentSizeLimit.java
> +    * The maximum size of the content
`The maximum size in bytes of the content` ?

2024-09-17 13:47 UTC, amanteaux commented on plume-web-jersey/src/main/java/com/coreoz/plume/jersey/security/control/ContentControlFeature.java
> +public class ContentControlFeature implements DynamicFeature {
Il faudrait documenter la classe et référencer : l'annotation à utiliser optionnellement pour changer la limite, la limite par défaut

2024-09-17 13:47 UTC, amanteaux commented on plume-web-jersey/src/main/java/com/coreoz/plume/jersey/security/control/ContentControlFeature.java
> +        private static final int DEFAULT_MAX_SIZE = 500;
En fait la limite par défaut devrait être fournie à la création de la feature Jersey. Comme ça la vraie valeur par défaut serait fournie dans la configuration du projet

2024-09-17 13:47 UTC, amanteaux commented on plume-web-jersey/src/main/java/com/coreoz/plume/jersey/security/control/ContentControlFeature.java
> +            final String headerContentLength = context.getHeaders().getFirst("Content-Length");
`HttpHeaders.CONTENT_LENGTH`

2024-09-17 13:47 UTC, amanteaux commented on plume-web-jersey/src/main/java/com/coreoz/plume/jersey/security/control/ContentControlFeature.java
> +            final Long declaredContentLength = headerContentLength == null ? -1 : Long.valueOf(headerContentLength);
Ici on devrait avoir un système "fail fast" : si déjà le content length déclaré est supérieur à `maxSize`, on stoppe tout de suite la requête.

Et donc ensuite dans `ContentSizeLimitInputStream` en maxSize, on fournit `declaredContentLength` (sachant que s'il est supérieur à `maxSize`, on aura déjà levé une exception)

2024-09-17 13:47 UTC, amanteaux commented on plume-web-jersey/src/main/java/com/coreoz/plume/jersey/security/control/ContentControlFeature.java
> +            private final long declaredContentLength;
A supprimer

2024-09-17 13:47 UTC, amanteaux commented on plume-web-jersey/src/main/java/com/coreoz/plume/jersey/security/control/ContentControlFeature.java
> +            private final InputStream contextInputStream;
`delegateInputStream` ?

2024-09-17 13:47 UTC, amanteaux commented on plume-web-jersey/src/main/java/com/coreoz/plume/jersey/security/control/ContentControlFeature.java
> +        public static final class ContentSizeLimitInputStream extends InputStream {
`SizeLimitingInputStream` ?

2024-09-17 13:47 UTC, amanteaux commented on plume-web-jersey/src/main/java/com/coreoz/plume/jersey/security/control/ContentControlFeature.java
> +            context.setInputStream(contextInputStream);
A quoi sert cette ligne ?

2024-09-17 13:47 UTC, amanteaux commented on plume-web-jersey/src/test/java/com/coreoz/plume/jersey/control/ContentSizeLimitTest.java
> +public class ContentSizeLimitTest {
Ce serait top en plus de faire un test d'intégration avec Grizzly et Jersey de manière à vérifier que la limite par défaut est bien prise en compte, et l'annotation aussi

2024-09-19 09:49 UTC, benoitvasseur commented on plume-web-jersey/src/main/java/com/coreoz/plume/jersey/security/control/ContentControlFeature.java
> +            context.setInputStream(contextInputStream);
Bah c'est une bonne question, je pensais que c'était nécessaire car le stream avait déjà été parcouru, mais enfait ça marche très bien sans.

2024-09-19 17:24 UTC, amanteaux requested changes

2024-09-19 17:24 UTC, amanteaux commented on plume-web-jersey/src/main/java/com/coreoz/plume/jersey/security/control/ContentControlFeature.java
> +            }
J'aurais bien rendu le header optionnel car il peut y avoir 2 cas où il n'est pas fourni :
- Pour les requêtes sans body
- Pour les requêtes envoyées en chunked encoding

2024-09-19 17:24 UTC, amanteaux commented on plume-web-jersey/src/main/java/com/coreoz/plume/jersey/security/control/ContentControlFeature.java
> +            }
Pour rendre le code cohérent, on pourrait juste initialiser headerContentLength avec maxSize

2024-09-19 17:24 UTC, amanteaux commented on plume-web-jersey/src/main/java/com/coreoz/plume/jersey/security/control/ContentControlFeature.java
> +@Singleton
A l'usage, on ne va pas instancier ça avec Guice, si ?

2024-09-19 17:24 UTC, amanteaux commented on plume-web-jersey/src/test/java/com/coreoz/plume/jersey/control/TestContentSizeResource.java
> +    @Path("/upload-default")
Idéalement, il faudrait faire un test avec @GET pour confirmer qu'il n'y a pas de header content length envoyé

2024-09-23 15:58 UTC, amanteaux commented on plume-web-jersey/src/main/java/com/coreoz/plume/jersey/security/control/ContentControlFeature.java
> +            }
C'est un peu cracra, tu vas lever des exceptions à chaque requête GET.
Ce serait mieux de faire le parsing seulement si le header est non nul.

Par exemple :
```suggestion
                int headerContentLength = maxSize; // default value for GET or chunked body
                String contentLengthHeader = context.getHeaders().getFirst(HttpHeaders.CONTENT_LENGTH);
                if (contentLengthHeader) {
                  try {
                    headerContentLength = Integer.parseInt(contentLengthHeader);
                  } catch (NumberFormatException e) {
                    logger.warn("Wrong content length header received: {}", contentLengthHeader);
                  }
                }
```

2024-09-23 16:24 UTC, merged