Update jersey
Coreoz/Plume pull request #37
Opened 2024-09-04 14:08 UTC by benoitvasseur

2024-09-17 14:42 UTC, amanteaux requested changes

2024-09-17 14:42 UTC, amanteaux commented on plume-conf/src/main/java/com/coreoz/plume/conf/ConfigProvider.java
> +import jakarta.inject.Singleton;
Il ne manque pas `jakarta.annotation-api` dans le fichier `pom.xml` de ce projet ?

2024-09-17 14:42 UTC, amanteaux commented on plume-db-querydsl-codegen/pom.xml
>  			<artifactId>querydsl-sql-codegen</artifactId>
Pour ça aussi il faudrait passer par Jakarta tant qu'à faire.

A priori on peut faire la transition complète avec https://github.com/querydsl/querydsl/issues/3371 et https://github.com/querydsl/querydsl/issues/3681

2024-09-17 14:42 UTC, amanteaux commented
cf issue #19

2024-09-18 15:37 UTC, benoitvasseur commented on plume-conf/src/main/java/com/coreoz/plume/conf/ConfigProvider.java
> +import jakarta.inject.Singleton;
Visiblement non, je ne vois pas d'annotation dans ce module (et la dépendance n'était pas pas présente avant)

2024-09-18 16:44 UTC, benoitvasseur commented on plume-db-querydsl-codegen/pom.xml
>  			<artifactId>querydsl-sql-codegen</artifactId>
vu ensemble, comme il n'y a pas de classifier jakarta pour querydsl-sql-codegen, on va juste retirer l'exclusion javax pour le moment
https://repo1.maven.org/maven2/com/querydsl/querydsl-sql-codegen/5.1.0/querydsl-sql-codegen-5.1.0.pom

2024-09-18 16:45 UTC, amanteaux commented on plume-conf/src/main/java/com/coreoz/plume/conf/ConfigProvider.java
> +import jakarta.inject.Singleton;
C'est étrange, elle vient d'où la dépendance ? :O

2024-09-18 17:12 UTC, merged